from pandas import DataFrame
from pandas import Series

numerics = [
    'pondera_dem',
    'edad',
    'NSEpuntaje',
    'minutos_radio_1',
    'minutos_radio_total',
    'horas_radio_total',
    'minutos_musica_1',
    'minutos_musica_total',
    'horas_musica_total',
    'minutos_diario_1',
    'minutos_diario_total',
    'horas_diario_total',
    'minutos_tv_1',
    'minutos_tv_total',
    'horas_tv_total',
    'minutos_internet_1',
    'minutos_internet_total',
    'horas_internet_total',
    'minutos_redes_1',
    'minutos_redes_total',
    'horas_redes_total',
    'minutos_videojuegos_1',
    'minutos_videojuegos_total',
    'horas_videojuegos_total'
    ]

frecs = [
    'frec_libros_cuentos',
    'frec_libros_novelas',
    'frec_libros_poesia',
    'frec_libros_ensayos',
    'frec_libros_escolares',
    'frec_libros_biografias',
    'frec_libros_teatro',
    'frec_libros_ciencia',
    'frec_libros_comics',
    'frec_libros_humor',
    'frec_libros_autoayuda',
    'frec_libros_historia',
    'frec_libros_politica',
    'frec_libros_salud',
    'frec_libros_divulgacion',
    'frec_libros_otros',
    'frec_genero_musica_folclore',
    'frec_genero_musica_rock_extranjero',
    'frec_genero_musica_rock_nacional',
    'frec_genero_musica_clasica',
    'frec_genero_musica_jazz',
    'frec_genero_musica_cumbia',
    'frec_genero_musica_reggaeton',
    'frec_genero_musica_salsa',
    'frec_genero_musica_melodica',
    'frec_genero_musica_pop',
    'frec_genero_musica_reggae',
    'frec_genero_musica_electronica',
    'frec_genero_musica_tango',
    'frec_cine_accion',
    'frec_cine_aventura',
    'frec_cine_scifi',
    'frec_cine_suspenso',
    'frec_cine_terror',
    'frec_cine_drama',
    'frec_cine_comedia',
    'frec_cine_romantico',
    'frec_cine_documental',
    'frec_cine_infantiles',
    'frec_cine_animacion',
    'frec_circo',
    'frec_feria_gastronomia',
    'frec_carnavales',
    'frec_penia_musical',
    'frec_fiesta_religiosa',
    'frec_fiesta_regional',
    'frec_kermes',
    'frec_monumentos',
    'frec_arquelogia',
    'frec_parque_nacional',
    'frec_muestra_pintura',
    'frec_muestra_escultura',
    'frec_muestra_fotografia',
    'frec_archivo_historico',
    'frec_presentacion_danza',
    'frec_feria_artesanal',
    'frec_centro_cultura',
    'frec_ferias_libro'
    ]

def dict_frecs_binary():
    mapper = {'NO FUE NUNCA': False,
              '1 VEZ EN EL ULTIMO AÑO': True,
              'ENTRE 1 Y 5 AÑOS': False, 
              'HACE MAS DE 5 AÑOS': False,
              'VARIAS VECES EN EL ULTIMO AÑO': True,
              'NUNCA': False,
              'TODOS O CASI TODOS LOS DIAS': True,
              'ALGUNOS DIAS POR SEMANA': True,
              'ALGUNA VEZ AL AÑO': False,
              'ALGUNAS VECES AL MES': False,
              'ALGUNA VEZ CADA 3 MESES': False,
              'NS/NC': False,
              'CASI NUNCA': False,
              'HABITUALMENTE': True,
              'DE VEZ EN CUANDO': True,
              'VARIAS VECES AL AÑO': True,
              'UNA VEZ AL AÑO': True
              }
    return mapper


def nse_denom(df:DataFrame) -> Series:
    mapper = {
        'AB': '1- Alto',
        'C1': '1- Alto',
        'C2': '2- Medio-Alto',
        'C3': '3- Medio',
        'D1': '4- Medio-Bajo',
        'D2': '5- Bajo',
        'E': '6- Marginal'
        }
    return df['NSEcat1'].map(mapper)